
export default interface TStockInformation {
    StockNumber: string,
    LastSalePrice: string,
    ChangePricePct: string,
    ComparePrice: string,
    Average: string,
    PriorClosePrice: string,
    CmprPct: string,
    ChangePrice: string,
    High52: string,
    Low52: string,
    Ceiling: string,
    Floor: string,
    ProjectedClose: string,
    HighPrice: string,
    LowPrice: string,
    TotalValue: string,
    Open1: string,
    Open2: string,
    TotalVolume: string,
    OpenVolume: string,
    OpenVolumePct: string,
    BuyVolume: string,
    SellVolume: string,
    SellVolumePct: string,
    StockFullName: string,
    StockSymbol: string,
};